# Generates a translation unit defining a std::string_view per engine shader,
# named after the file (batch_vs.glsl -> k2::embedded_shaders::batch_vs).
# Invoked with -DSHADER_DIR=... -DOUTPUT=...

file(GLOB shader_files "${SHADER_DIR}/*.glsl")
list(SORT shader_files)

set(body "// Generated by cmake/embed_shaders.cmake from src/rendering/shaders — do not edit.\n")
string(APPEND body "#include \"rendering/embedded_shaders.hpp\"\n\nnamespace k2::embedded_shaders {\n")
foreach(file IN LISTS shader_files)
    get_filename_component(name "${file}" NAME_WE)
    file(READ "${file}" content)
    string(APPEND body "\nconst std::string_view ${name} = R\"k2embed(${content})k2embed\";\n")
endforeach()
string(APPEND body "\n}\n")

file(WRITE "${OUTPUT}" "${body}")
